version: '3.9'

services:
  node:
    build: .
    container_name: web
    ports:
      - "5555:5000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: ["/bin/sh", "./entrypoint.sh"]
    networks:
      - wingwizard
    depends_on:
      - postgres
  
  postgres:
    image: postgres:alpine
    restart: always
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wingwizard
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./pg_hba.local.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - wingwizard

networks:
  wingwizard:
    name: wingwizard
    driver: bridge